title: Jekyll Starter Test
description: A testing repo for jekyll
permalink: /:slugified_categories/:title/

date_format: "%b %-d, %Y"

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
